config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

Rails.application.default_url_options = {host: Rails.configuration.app.domain, trailing_slash: true}

Rails.application.routes.draw do
  draw :api_routes

  namespace :backend do
    resources :accounts, except: [:show]

    resources :users, except: [:show] do
      member do
        put "send_welcome"
      end
    end

    authenticate :user, (->(u) { u.admin? }) do
      mount Sidekiq::Web => "/workers"
    end

    root to: "base#dashboard"
  end

  mount ActionCable.server => "/cable"

  devise_for :users,
    skip: %i[sessions registrations],
    controllers: {registrations: "registrations"}

  as :user do
    get "signup" => "accounts#new", :as => :new_registration
    post "signup" => "accounts#create", :as => :registration
    get "settings" => "registrations#edit", :as => :edit_user_registration
    patch "settings" => "registrations#update", :as => :update_user_registration
    get "signin" => "sessions#new", :as => :new_user_session
    post "signin" => "sessions#create", :as => :user_session
    delete "signout" => "sessions#destroy", :as => :destroy_user_session
  end

  resource :me, controller: :current_user, only: [] do
    get :otp
    get :otp_qrcode
    post :otp_backup_codes
    post :enable_otp
    post :disable_otp
  end

  resource :account, only: %i[edit update]

  resource :password, only: %i[edit update]

  resources :invoices do
    collection do
      put "archive" => "invoices#archive_all"
    end
    member do
      put :generate_positions
      put :charge
      put :pay
      put :archive
      put :send_mail
      post :send_test_mail
      get "/pdf/:pdf" => "invoices#pdf", :as => :pdf, :defaults => {format: :pdf}
      get "/timesheet-pdf/:pdf" => "invoices#timesheet", :as => :timesheet_pdf, :defaults => {format: :pdf}
    end
  end

  resources :offers do
    member do
      get "/pdf/:pdf" => "offers#pdf", :as => :pdf, :defaults => {format: :pdf}
    end
  end

  resource :timesheet, only: [:show]

  resource :template, only: [] do
    template "blank"
    template "datepicker"
    template "month_timers"
    template "day_timesheets"
    template "week_timesheets"
    template "timer_modal_timesheets"
    template "task_modal_timesheets"
    template "index_logbooks"
  end

  resources :positions, only: %i[new destroy]

  resources :customers, only: %i[edit update]
  resources :projects, except: [:destroy] do
    member do
      put :unarchive
    end

    resources :tasks, only: %i[index create]
  end

  resources :timers, only: [] do
    collection do
      get :uninvoiced
    end
  end

  resources :expenses, except: [:show]
  resources :expense_imports, only: %i[new create]

  resource :dropbox, controller: "dropbox", only: [:show] do
    collection do
      get :start
      get :activate
      get :deactivate
    end
  end

  draw :frontend_routes

  get "impressum" => "base#impressum"
  get "privacy" => "base#privacy"
  get "terms" => "base#terms"

  match "404" => "errors#not_found", :via => :all
  match "422" => "errors#server_error", :via => :all
  match "500" => "errors#server_error", :via => :all

  root to: "base#index"
end

app/models/project.rb
# frozen_string_literal: true

require "business_time"

class Project < ApplicationRecord
  include RoutingConcern

  DEFAULT_ROUND_UP_OPTIONS = {
    "Nicht aufrunden" => 0.minutes,
    "Auf 15 Minuten" => 15.minutes,
    "Auf 30 Minuten" => 30.minutes,
    "Auf 1 Stunde" => 60.minutes
  }.freeze

  belongs_to :customer
  has_many :invoices, dependent: :destroy
  has_many :offers, dependent: :destroy
  has_many :tasks, dependent: :destroy, inverse_of: :project
  has_many :timers, through: :tasks

  validates :name, :rate, presence: true

  accepts_nested_attributes_for :tasks, allow_destroy: true

  delegate :name, to: :customer, prefix: true

  before_save :set_working_days

  include Workflow
  workflow do
    state :active do
      event :archive, transitions_to: :archived
    end
    state :archived do
      event :unarchive, transitions_to: :active
    end
  end

  def set_working_days
    return if start_date.blank? || end_date.blank?

    if federal_state.present?
      GermanHoliday.where(federal_state: ["NATIONAL", federal_state]).find_each do |holiday|
        BusinessTime::Config.holidays << holiday.date
      end
    end

    self.business_days = start_date.business_days_until(end_date)
  end

  def label
    name_with_customer
  end

  def self.active
    with_active_state
  end

  def self.archived
    with_archived_state
  end

  def self.with_budget
    where.not(budget: 0).where(budget_on_dashboard: true)
  end

  def url
    api_v1_project_url(self)
  end

  def name_with_customer
    "#{customer.name} - #{name}"
  end

  def timer_values
    values = 0.0
    timers.each do |timer|
      values += timer.value.to_d if timer.value.present?
    end
    values
  end

  def timer_values_billable
    values = 0.0
    timers.billable.each do |timer|
      values += timer.value.to_d if timer.value.present?
    end
    values
  end

  def timer_values_invoiced
    values = 0.0
    timers.each do |timer|
      values += timer.value.to_d if timer.value.present? && timer.position_id.present?
    end
    values
  end

  def timer_values_uninvoiced
    values = 0.0
    timers.billable.each do |timer|
      values += timer.value.to_d if timer.value.present? && timer.position_id.blank?
    end
    values
  end

  def invoice_values
    values = 0.0
    invoices.each do |invoice|
      values += invoice.value.to_d
    end
    values
  end

  def budget_percent
    if budget_hours.present?
      timer_values / budget_hours * 100
    else
      invoice_values / budget * 100
    end
  end

  def budget_percent_invoiced
    return if budget_hours.blank?

    timer_values_invoiced / budget_hours * 100
  end

  def budget_percent_uninvoiced
    return if budget_hours.blank?

    timer_values_uninvoiced / budget_hours * 100
  end
end

app/controllers/api/v1/projects_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class ProjectsController < Api::BaseController
      rescue_from ActiveRecord::RecordNotFound do |_exception|
        not_found(I18n.t("messages.record_not_found.project", id: params[:id]))
      end

      def index
        authorize! :index, Project

        scope = current_account.projects.includes(:customer)

        state = params.fetch(:state, nil)
        scope = if state.present? && Project.workflow_spec.state_names.include?(state.to_sym)
          scope.where(workflow_state: state)
        else
          scope.where(workflow_state: :active)
        end

        scope = scope.where.not(id: without_ids) if without_ids

        sort = params.fetch(:sort, nil)
        @projects = if sort.present? && sort == "used"
          scope.includes(:timers).order("timers.created_at desc nulls last")
        else
          scope.order(name: :asc)
        end
      end

      def show
        @project = current_account.projects.find(params[:id])
        authorize! :show, @project
      end

      def destroy
        @project = current_account.projects.find(params[:id])
        authorize! :destroy, @project

        if @project.invoices.present?
          Rails.logger.info "Project Destroy Failed: Invoices present"
          render json: ValidationError.new("project.destroy_failure_dependency"), status: :bad_request
        elsif @project.destroy
          render json: {message: resource_message(:project, :destroy, :success)}, status: :ok
        else
          Rails.logger.info "Project Destroy Failed: #{@project.errors.full_messages.to_yaml}"
          render json: ValidationError.new("project.destroy", @project.errors), status: :bad_request
        end
      end

      def archive
        @project = current_account.projects.find(params[:id])
        authorize! :archive, @project
        if @project.archived?
          Rails.logger.info "Project Archive Failed"
          render json: ValidationError.new("project.archive"), status: :bad_request
        else
          @project.archive!
          @project.save
          render json: {message: resource_message(:project, :archive, :success)}, status: :ok
        end
      end

      private def without_ids
        @without_ids ||= params[:withoutIds]
      end

      private def project_params
        @project_params ||= params.permit(
          :customer_id,
          :name,
          :rate,
          :budget,
          :budget_on_dashboard,
          tasks_attributes: %i[
            id
            name
            project_id
            _destroy
          ]
        )
      end
    end
  end
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  include ResourceHelper

  before_action :set_active_nav
  before_action :check_dependencies, only: [:new]

  def index
    authorize! :read, Project

    state = params.fetch(:state, nil)
    scope = current_account.projects.includes(:customer, :timers)
    scope = if state.present? && Project.workflow_spec.state_names.include?(state.to_sym)
      scope.where(workflow_state: state)
    else
      scope.where(workflow_state: :active)
    end

    @projects = scope.order("#{sort_column} #{sort_direction}")
      .page(params.fetch(:page, nil))
      .per(20)
    @projects_by_customer = @projects.group_by(&:customer)
  end

  def show
    authorize! :read, project
    @project_budget_chart_data = Charts::ProjectBudgetService.new(project, project.timers.billable).data
  end

  def new
    authorize! :create, Project
    @project = if customer
      customer.projects.new
    else
      current_account.projects.new
    end
  end

  def edit
    authorize! :update, project
  end

  def create
    authorize! :create, Project
    if project.save
      redirect_to project_path(project), flash: {success: resource_message(:project, :create, :success)}
    else
      flash.now[:alert] = resource_message(:project, :create, :failure)
      render "new"
    end
  end

  def update
    authorize! :update, project
    if project.update(project_params)
      redirect_to project_path(project), flash: {success: resource_message(:project, :update, :success)}
    else
      flash.now[:alert] = resource_message(:project, :update, :failure)
      render "edit"
    end
  end

  def unarchive
    authorize! :archive, project
    if project.unarchive!
      redirect_to projects_path, flash: {success: I18n.t(:"messages.project.unarchive.success")}
    else
      redirect_to projects_path, alert: I18n.t(:"messages.project.unarchive.failure")
    end
  end

  private def sort_column
    if (Project.column_names + %w[customers.name]).include?(params[:sort])
      params[:sort]
    else
      "customers.name"
    end
  end
  helper_method :sort_column

  private def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

  private def set_active_nav
    @active_nav = "projects"
  end

  private def customers
    @customers ||= current_account.customers
  end
  helper_method :customers

  private def customer
    @customer ||= current_account.customers.find_by(id: params.fetch(:customer_id, nil))
  end

  private def project_params
    @project_params ||= params.require(:project).permit(
      :customer_id, :name, :rate, :budget, :budget_hours, :round_up, :invoice_addition,
      :budget_on_dashboard, :start_date, :end_date, tasks_attributes: %i[
        id name project_id billable _destroy
      ]
    )
  end

  private def project
    @project ||= Project.where(id: params.fetch(:id, nil)).first
    @project ||= current_account.projects.new project_params
  end
  helper_method :project

  private def check_dependencies
    return if current_account.address.present?

    redirect_to "#{edit_account_path}#address", alert: I18n.t(:"messages.missing_address")
  end
end

app/helpers/project_helper.rb
# frozen_string_literal: true

module ProjectHelper
  def budget_progress(project)
    if project.budget_percent.to_f > 90.0
      "progress-bar-danger"
    elsif project.budget_percent.to_f > 70.0
      "progress-bar-warning"
    else
      "progress-bar-success"
    end
  end
end

app/views/projects/_form.slim
= form_for project do |form|
  .row
    .col-xs-12.col-md-6
      .form-group.selectize class=form_error?(project, :customer_id)
        = form.collection_select :customer_id, customers, :id, :name, {include_blank: ""}, {placeholder: I18n.t(:"helpers.prompt.project.customer_id"), class: "js-customer-selectize"}
        = form_errors project, :customer_id
    .col-xs-12.col-md-6
      .form-group class=form_error?(project, :name)
        = form.text_field :name, placeholder: I18n.t(:"helpers.placeholder.name"), class: 'form-control'
        = form_errors project, :name
  .row
    .col-xs-12.col-md-6.form-group class=form_error?(project, :start_date)
      .input-group.datepicker
        = form.label :start_date, class: "input-group-addon"
        = form.date_field :start_date, class: 'form-control', "data-value" => form.object.start_date
        span.input-group-btn
          button.btn.btn-default type="button"
            i.fa.fa-calendar

    .col-xs-12.col-md-6.form-group class=form_error?(project, :end_date)
      .input-group.datepicker
        = form.label :end_date, class: "input-group-addon"
        = form.date_field :end_date, class: 'form-control', "data-value" => form.object.end_date
        span.input-group-btn
          button.btn.btn-default type="button"
            i.fa.fa-calendar
  .row
    .col-xs-6.col-md-3.form-group class=form_error?(project, :rate)
      = form.label :rate
      .input-group
        = form.number_field :rate, class: 'form-control text-right'
        span.input-group-addon €/Std.
      = form_errors project, :rate

    .col-xs-6.col-md-3.form-group class=form_error?(project, :budget)
      = form.label :budget
      .input-group
        = form.number_field :budget, class: 'form-control text-right', step: 'any'
        span.input-group-addon €
      = form_errors project, :budget

    .col-xs-6.col-md-3.form-group class=form_error?(project, :budget_hours)
      = form.label :budget_hours
      .input-group
        = form.number_field :budget_hours, class: 'form-control text-right', step: 'any'
        span.input-group-addon h
      = form_errors project, :budget_hours

    .col-xs-12.col-md-3.form-group class=form_error?(project, :budget_on_dashboard)
      .checkbox
        = form.check_box :budget_on_dashboard
        = form.label :budget_on_dashboard
        = form_errors project, :budget_on_dashboard

  .row
    .col-xs-6.col-md-3
      p.form-control-static.text-right
        = I18n.t(:"helpers.label.project.round_up")
    .col-xs-6.col-md-3
      .form-group.selectize class=form_error?(project, :round_up)
        select.js-customer-selectize#project_round_up name="project[round_up]"
          - Project::DEFAULT_ROUND_UP_OPTIONS.each do |key, value|
            option value=value selected=(project.round_up.to_f == value)
              = key
        = form_errors project, :round_up
  .row
    .col-xs-6.form-group class=form_error?(project, :invoice_addition)
      = form.label :invoice_addition
      = form.text_area :invoice_addition, class: 'form-control'
      = form_errors project, :invoice_addition

  fieldset
    legend Aufgaben:
    .row#tasks
      = form.fields_for :tasks, project.tasks do |builder|
        = render 'task_fields', fields: builder
    .row
      .col-xs-12
        .btn-group-responsive.pull-right
          = link_to_add_fields form, :tasks, name: I18n.t(:"actions.add"), class: "btn btn-default", target: "#tasks" do
            i.fa.fa-plus
            '
            = I18n.t(:"actions.add_task")

  br
  hr

  .btn-group-responsive
    button.btn.btn-primary.btn-lg type="submit"
      = I18n.t(:"actions.save")
    '
    a.btn.btn-default href=projects_path data-notyConfirm=I18n.t(:"messages.confirm.form.cancel")
      = I18n.t(:"actions.cancel")

app/views/projects/_list.haml
- @projects_by_customer.each do |customer, projects|
  .panel.panel-list{class: "panel-default"}
    .panel-heading
      .panel-title
        .row
          .col-xs-8.col-md-4.name
            %a{href: edit_customer_path(customer)}
              %strong
                = customer.name
          .col-md-2.hidden-xs.hidden-sm
            %span
              = I18n.t(:"labels.defaults.budget")
          .col-md-4.hidden-xs.hidden-sm
            %span
              = I18n.t(:"labels.defaults.hours")
          .col-xs-4.col-md-2
            .panel-list-action.pull-right
              %a.btn.btn-default{href: new_project_path(customer_id: customer), title: I18n.t(:"nav.subnav.new_project_for_customer", customer: customer.name), data: {toggle: 'tooltip'}}
                %i.fa.fa-plus
    .list-group
      = render partial: "projects/show", collection: projects.sort_by(&:name), as: :project

app/views/projects/_show.slim
.list-group-item
  .row
    .col-xs-12.col-md-4.project-name
      a.plain href=project_path(project)
        b = project.name
    .col-xs-12.col-md-2.project-budget
      - unless project.budget.zero?
        b = number_to_currency(project.budget)
    .col-xs-12.col-md-4.project-progress
      .budget-label
        - if project.budget.present? && !project.budget.zero?
          .progress.budget-progress.progress-slim.text-center
            .progress-bar class=budget_progress(project) role="progressbar" aria-valuemin="0" aria-valuemax="100" style="width: #{project.budget_percent}%"
        - else
          = number_to_currency project.timer_values, unit: "h", precision: 2
    .col-xs-12.col-md-2.actions
      - if project.active?
        .pull-right.hidden-xs.hidden-sm
          .dropdown
            button.btn.btn-default.btn-sm.dropdown-toggle type="button" data-toggle="dropdown" aria-expanded="false"
              = I18n.t(:"labels.defaults.actions")
              '
              span.caret
            ul.dropdown-menu.dropdown-menu-right role="menu"
              li
                a href=project_path(project)
                  = I18n.t(:"actions.show")
              li
                a href=new_invoice_path(project_id: project)
                  i.fa.fa-plus
                  '
                  = I18n.t(:"actions.add_invoice")
              li
                a href=edit_project_path(project)
                  i.fa.fa-edit
                  '
                  = I18n.t(:"actions.edit")
              li.divider
              li
                a href=archive_api_v1_project_url(project) data-redirect=projects_path data-method="PUT" data-notyConfirm=I18n.t(:"messages.confirm.project.archive")
                  i.fa.fa-archive
                  '
                  = I18n.t(:"actions.archive")
        .btn-group.btn-group-justified.visible-xs.visible-sm
          a.btn.btn-default href=project_path(project)
            = I18n.t(:"actions.show")
          a.btn.btn-default href=new_invoice_path(project_id: project) title=I18n.t(:"actions.add_invoice")
            i.fa.fa-plus
            span.hidden-xs.hidden-sm= I18n.t(:"actions.add_invoice")
          a.btn.btn-default href=edit_project_path(project) title=I18n.t(:"actions.edit")
            i.fa.fa-edit
            span.hidden-xs.hidden-sm= I18n.t(:"actions.edit")
          a.btn.btn-default href=archive_api_v1_project_url(project) data-redirect=projects_path data-method="PUT" data-notyConfirm=I18n.t(:"messages.confirm.project.archive") title=I18n.t(:"actions.archive")
            i.fa.fa-archive
            span.hidden-xs.hidden-sm= I18n.t(:"actions.archive")
      - else
        .pull-right.hidden-xs.hidden-sm
          = link_to I18n.t(:"actions.unarchive"), unarchive_project_path(project), class: "btn btn-default", method: :put
        .btn-group.btn-group-sm.btn-group-justified.visible-xs.visible.sm
          = link_to I18n.t(:"actions.unarchive"), unarchive_project_path(project), class: "btn btn-default", method: :put

app/views/projects/_task_fields.haml
.col-xs-12.col-md-6.fields
  .form-group{class: form_error?(fields.object, :name)}
    .input-group
      = fields.text_field :name, placeholder: I18n.t(:"helpers.placeholder.name"), class: 'form-control'
      %span.input-group-addon
        .checkbox
          = fields.check_box :billable
          = fields.label :billable
      %span.input-group-btn
        = link_to_delete_fields fields, name: I18n.t(:"actions.delete"), class: "btn btn-danger" do
          %i.fa.fa-trash
    = form_errors fields.object, :name

  .clearfix

app/views/projects/_tasks_panel.haml
- context ||= 'info'
.panel{class: "panel-#{context}"}
  .list-group.tasks-list
    - tasks.each do |task|
      %a.list-group-item{href: ""}
        = task.name
        %span.pull-right.badge
          = I18n.t("labels.task.billable.#{task.billable}")
    - if tasks.empty?
      %span.list-group-item
        = I18n.t(:"labels.table.blank.task")

app/views/projects/_timers_panel.slim
- context ||= 'info'
javascript:
  window.projectId = "#{project.id}";

#timers-calendar.timers-calendar ng-strict-di=true data-turbolinks="false"
  .row ng-view=true

app/views/projects/edit.haml
- content_for :title do
  = I18n.t(:"meta.title.project.edit")

.row#edit-project
  .col-xs-12.col-md-12

    .row
      .col-xs-12.col-md-8
        %h1
          = I18n.t(:"headlines.project.edit")

      .col-xs-12.col-md-4
        .btn-group.btn-group-justified-responsive.pull-right.resource-nav
          = link_to I18n.t(:"nav.subnav.back"), :back, class: "btn btn-default"

    = render "form"

app/views/projects/edit.slim
- content_for :title do
  = I18n.t(:"meta.title.project.edit")
.row#edit-project
  .col-xs-12.col-md-12
    .row
      .col-xs-12.col-md-8
        h1= I18n.t(:"headlines.project.edit")
      .col-xs-12.col-md-4
        .btn-group.btn-group-justified-responsive.pull-right.resource-nav
          = link_to I18n.t(:"nav.subnav.back"), :back, class: "btn btn-default"
          a.btn.btn-danger href=api_v1_project_url(project) data-redirect=projects_path data-method="DELETE" data-notyConfirm= I18n.t(:"messages.confirm.delete")
            i.fa.fa-trash
            '
            = I18n.t(:"actions.delete")
    = render "form"

app/views/projects/index.haml
- content_for :title do
  = I18n.t(:"meta.title.project.index")

.row#projects
  .col-xs-12.col-md-12

    .row
      .col-xs-12.col-md-8
        %h1
          - if params.fetch(:state, nil)
            = I18n.t(:"headlines.project.index_archived")
          - else
            = I18n.t(:"headlines.project.index")

      .col-xs-12.col-md-4
        .btn-group.btn-group-justified-responsive.pull-right.resource-nav
          %a.btn.btn-primary{href: new_project_path}
            %i.fa.fa-plus
            = I18n.t(:"nav.subnav.new_project")

    .row
      .col-xs-12.col-md-6.filters
        .btn-group
          - if params.fetch(:state, nil)
            %a.btn.btn-default{href: url_for(state: nil)}
              = I18n.t(:"filter.project_state.all")
          - else
            %a.btn.btn-default{href: url_for(state: :archived)}
              = I18n.t(:"filter.project_state.archived")
      .col-xs-12.col-md-6
        = paginate @projects

    = render partial: "list"

    - if @projects.blank?
      = render partial: "shared/blank"

    .row
      .col-xs-12
        = paginate @projects

app/views/projects/new.haml
- content_for :title do
  = I18n.t(:"meta.title.project.new")

.row#new-project
  .col-xs-12.col-md-12

    .row
      .col-xs-12.col-md-8
        %h1
          = I18n.t(:"headlines.project.new")

      .col-xs-12.col-md-4
        .btn-group.btn-group-justified-responsive.pull-right.resource-nav
          = link_to I18n.t(:"nav.subnav.back"), :back, class: "btn btn-default"

    = render "form"

app/views/projects/show.slim
- content_for :title do
  = project.name
.row#show-project
  .col-xs-12.col-md-12
    .row
      .col-xs-12.col-md-7
        h1
          = project.name
      .col-xs-12.col-md-5
        .btn-group.btn-group-justified-responsive.pull-right.resource-nav
          = link_to I18n.t(:"nav.subnav.back"), projects_path, class: "btn btn-default"
          a.btn.btn-primary href=edit_project_path(project)
            i.fa.fa-edit
            '
            span.hidden-xs.hidden-sm.hidden-md= I18n.t(:"actions.edit")
    .row
      .col-xs-12.col-md-12
        javascript:
          window.projectBudgetChartData = #{{@project_budget_chart_data.to_json}};
        .panel.panel-default
          .panel-heading
            .panel-title
              strong= I18n.t(:"labels.panels.charts.project_budget")
          .panel-body
            .chart.chart-big
              .chart-inner#project-budget-chart
            .row
              .col-xs-12.panel-progress
                .progress.progress-slim.text-center
                  .progress-bar class=budget_progress(project) role="progressbar" aria-valuemin="0" aria-valuemax="100" style="width: #{project.budget_percent}%"
            .row
              .col-xs-6.col-md-3.panel-box.panel-box-bottom
                h2 Erfasste Stunden
                .highlight
                  = number_to_currency(project.timer_values, unit: "h", precision: 2)
                .subline
                  a href="#{timesheet_path(project_id: project)}/#/day/#{I18n.l(Time.zone.now.to_date, format: :db)}/new"
                    i.fa.fa-clock-o
                    '
                    = I18n.t(:"actions.add_timer")
              .col-xs-6.col-md-3.panel-box.panel-box-bottom
                h2 Verbleibende Stunden
                - if project.budget_hours.present? && !project.budget_hours.zero?
                  .highlight
                    = number_to_currency((project.budget_hours - project.timer_values_billable), unit: "h", precision: 2)
                    '
                    small
                      = "("
                      = ((project.budget_hours - project.timer_values_billable) / 8).round
                      '
                      = I18n.t('labels.defaults.days')
                      = ")"
                - else
                  .highlight.blank
                    = I18n.t(:"labels.defaults.na")
                .subline
                  - if project.budget_hours.present? && !project.budget_hours.zero?
                    .row
                      .col-xs-4.text-left Gesamt
                      .col-xs-8.text-right
                        = number_to_currency(project.budget_hours, unit: "h", precision: 2)
                        '
                        = "("
                        = (project.budget_hours / 8).round
                        '
                        = I18n.t('labels.defaults.days')
                        = ")"
              .col-xs-6.col-md-3.panel-box.panel-box-bottom
                h2 Verbleibendes Budget
                - if project.budget.present? && !project.budget.zero?
                  .highlight
                    = number_to_currency (project.budget - project.invoice_values)
                - else
                  .highlight.blank
                    = I18n.t(:"labels.defaults.na")
                .subline
                  - if project.budget.present? && !project.budget.zero?
                    .row
                      .col-xs-4.text-left Gesamt
                      .col-xs-8.text-right= number_to_currency(project.budget)
              .col-xs-6.col-md-3.panel-box.panel-box-bottom
                h2 Offener Betrag
                - if project.rate.present?
                  .highlight
                    = number_to_currency project.timer_values_uninvoiced * project.rate
                - else
                  .highlight.blank
                    = I18n.t(:"labels.defaults.na")
                .subline
                  a href=new_invoice_path(project_id: project)
                    i.fa.fa-plus
                    '
                    = I18n.t(:"actions.add_invoice")
    .row
      .col-xs-12.col-md-12
    .row
      .col-xs-12.col-md-12.nav-tabs-list.nav-tabs-full-width
        ul.nav.nav-tabs role="tablist"
          li.active
            a href="#timers" role="tab" data-toggle="tab"
              = I18n.t(:"labels.defaults.timers")
          li
            a href="#offers" role="tab" data-toggle="tab"
              = I18n.t(:"labels.defaults.offers")
          li
            a href="#invoices" role="tab" data-toggle="tab"
              = I18n.t(:"labels.defaults.invoices")
          li
            a href="#tasks" role="tab" data-toggle="tab"
              = I18n.t(:"labels.defaults.tasks")
        .tab-content
          .tab-pane.active#timers
            = render "timers_panel", timers: project.timers.includes(:task), context: "default"
          .tab-pane#offers
            = render "base/offers_panel", offers: project.offers.includes(:customer), context: "default"
          .tab-pane#invoices
            = render "base/invoices_panel", invoices: project.invoices.includes(:customer), context: "default"
          .tab-pane#tasks
            = render "tasks_panel", tasks: project.tasks, context: "default"