config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

Rails.application.default_url_options = {host: Rails.configuration.app.domain, trailing_slash: true}

Rails.application.routes.draw do
  draw :api_routes

  namespace :backend do
    resources :accounts, except: [:show]

    resources :users, except: [:show] do
      member do
        put "send_welcome"
      end
    end

    authenticate :user, (->(u) { u.admin? }) do
      mount Sidekiq::Web => "/workers"
    end

    root to: "base#dashboard"
  end

  mount ActionCable.server => "/cable"

  devise_for :users,
    skip: %i[sessions registrations],
    controllers: {registrations: "registrations"}

  as :user do
    get "signup" => "accounts#new", :as => :new_registration
    post "signup" => "accounts#create", :as => :registration
    get "settings" => "registrations#edit", :as => :edit_user_registration
    patch "settings" => "registrations#update", :as => :update_user_registration
    get "signin" => "sessions#new", :as => :new_user_session
    post "signin" => "sessions#create", :as => :user_session
    delete "signout" => "sessions#destroy", :as => :destroy_user_session
  end

  resource :me, controller: :current_user, only: [] do
    get :otp
    get :otp_qrcode
    post :otp_backup_codes
    post :enable_otp
    post :disable_otp
  end

  resource :account, only: %i[edit update]

  resource :password, only: %i[edit update]

  resources :invoices do
    collection do
      put "archive" => "invoices#archive_all"
    end
    member do
      put :generate_positions
      put :charge
      put :pay
      put :archive
      put :send_mail
      post :send_test_mail
      get "/pdf/:pdf" => "invoices#pdf", :as => :pdf, :defaults => {format: :pdf}
      get "/timesheet-pdf/:pdf" => "invoices#timesheet", :as => :timesheet_pdf, :defaults => {format: :pdf}
    end
  end

  resources :offers do
    member do
      get "/pdf/:pdf" => "offers#pdf", :as => :pdf, :defaults => {format: :pdf}
    end
  end

  resource :timesheet, only: [:show]

  resource :template, only: [] do
    template "blank"
    template "datepicker"
    template "month_timers"
    template "day_timesheets"
    template "week_timesheets"
    template "timer_modal_timesheets"
    template "task_modal_timesheets"
    template "index_logbooks"
  end

  resources :positions, only: %i[new destroy]

  resources :customers, only: %i[edit update]
  resources :projects, except: [:destroy] do
    member do
      put :unarchive
    end

    resources :tasks, only: %i[index create]
  end

  resources :timers, only: [] do
    collection do
      get :uninvoiced
    end
  end

  resources :expenses, except: [:show]
  resources :expense_imports, only: %i[new create]

  resource :dropbox, controller: "dropbox", only: [:show] do
    collection do
      get :start
      get :activate
      get :deactivate
    end
  end

  draw :frontend_routes

  get "impressum" => "base#impressum"
  get "privacy" => "base#privacy"
  get "terms" => "base#terms"

  match "404" => "errors#not_found", :via => :all
  match "422" => "errors#server_error", :via => :all
  match "500" => "errors#server_error", :via => :all

  root to: "base#index"
end

app/controllers/current_user_controller.rb
# frozen_string_literal: true

class CurrentUserController < ApplicationController
  def otp
    authorize! :update, current_user
    return if current_user.reload.otp_required_for_login?

    current_user.otp_secret = User.generate_otp_secret
    current_user.save
  end

  def otp_qrcode
    authorize! :update, current_user
    uri = current_user.otp_provisioning_uri(current_user.email, issuer: Rails.configuration.app.name)
    qr = RQRCode::QRCode.new(uri, level: :l)

    send_data qr.as_svg(color: "428bca"), type: "image/svg+xml", disposition: "inline"
  end

  def otp_backup_codes
    authorize! :update, current_user
    if current_user.reload.otp_required_for_login?
      @codes = current_user.generate_otp_backup_codes!
      current_user.save!
      flash.now[:success] = I18n.t(:"messages.backup_codes", scope: "devise.otp")
      render "otp"
    else
      redirect_to "#{edit_user_registration_path}#security"
    end
  end

  def enable_otp
    authorize! :update, current_user
    if current_user.validate_and_consume_otp!(otp_attempt)
      current_user.otp_required_for_login = true
      @codes = current_user.generate_otp_backup_codes!
      current_user.save!
      flash.now[:success] = I18n.t(:"messages.enable.success", scope: "devise.otp")
    else
      flash.now[:alert] = I18n.t(:"messages.enable.failure", scope: "devise.otp")
    end
    render "otp"
  end

  def disable_otp
    authorize! :update, current_user
    if current_user.validate_and_consume_otp!(otp_attempt)
      current_user.otp_secret = User.generate_otp_secret
      current_user.otp_required_for_login = false
      current_user.save!
      redirect_to "#{edit_user_registration_path}#security", flash: {success: I18n.t(:"messages.disable.success", scope: "devise.otp")}
    else
      flash.now[:alert] = I18n.t(:"messages.disable.failure", scope: "devise.otp")
      render "otp"
    end
  end

  private def otp_attempt
    params.fetch(:user, {}).fetch(:otp_attempt, nil)
  end
end

app/views/current_user/otp.slim
- content_for :title do
  = I18n.t(:"meta.title.devise.otp")
.row
  .col-xs-12.col-md-12
    = render "users/header", path: "#{edit_user_registration_path}#security"

    .row
      .col-xs-12.col-lg-2.col-md-3.col-sm-3
        = render "users/nav", path: edit_user_registration_path, active: "security"

      .col-xs-12.col-lg-10.col-md-9.col-sm-9
        .tab-pane#security
          fieldset
            legend
              = I18n.t(:title, scope: 'devise.otp')
            p
              == I18n.t(:explain, scope: 'devise.otp',
                        google_auth_link: 'https://support.google.com/accounts/answer/1066447?hl=de',
                        one_password_link: 'https://agilebits.com/onepassword',
                        authy_link: 'https://www.authy.com/')

            - if current_user.reload.otp_required_for_login?
              - if @codes.present?
                p
                  = I18n.t(:backup_explain, scope: 'devise.otp')
                .row
                  .col-xs-12.col-md-4
                    pre
                      == @codes.join("<br>")
              - else
                p
                  = link_to I18n.t(:backup_codes, scope: 'devise.otp'), otp_backup_codes_me_path, method: :post, class: "btn btn-warning"

              hr

              = form_for(current_user, url: [:disable_otp, :me], html: { method: :post }) do |f|
                p
                  = I18n.t(:disable_explain, scope: 'devise.otp')
                .row
                  .col-xs-12.col-md-4
                    = f.text_field :otp_attempt, autocomplete: :off, placeholder: I18n.t(:otp_token, scope: 'devise.otp'), class: "form-control"

                hr
                  .btn-group-responsive
                    button.btn.btn-primary.btn-lg
                      = I18n.t(:disable, scope: 'devise.otp')
            - else
              = form_for(current_user, url: [:enable_otp, :me], html: { method: :post }) do |f|
                p
                  = I18n.t(:enable_explain, scope: 'devise.otp')
                .row
                  .col-xs-12.col-md-6
                    pre
                      = current_user.otp_provisioning_uri(current_user.email, issuer: Rails.configuration.app.name)
                    = image_tag otp_qrcode_me_url, class: "otp-qrcode"
                br
                .row
                  .col-xs-12.col-md-4
                    = f.text_field :otp_attempt, autocomplete: :off, placeholder: I18n.t(:otp_token, scope: 'devise.otp'), class: "form-control"

                hr
                  .btn-group-responsive
                    button.btn.btn-primary.btn-lg
                      = I18n.t(:enable, scope: 'devise.otp')