config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

Rails.application.default_url_options = {host: Rails.configuration.app.domain, trailing_slash: true}

Rails.application.routes.draw do
  draw :api_routes

  namespace :backend do
    resources :accounts, except: [:show]

    resources :users, except: [:show] do
      member do
        put "send_welcome"
      end
    end

    authenticate :user, (->(u) { u.admin? }) do
      mount Sidekiq::Web => "/workers"
    end

    root to: "base#dashboard"
  end

  mount ActionCable.server => "/cable"

  devise_for :users,
    skip: %i[sessions registrations],
    controllers: {registrations: "registrations"}

  as :user do
    get "signup" => "accounts#new", :as => :new_registration
    post "signup" => "accounts#create", :as => :registration
    get "settings" => "registrations#edit", :as => :edit_user_registration
    patch "settings" => "registrations#update", :as => :update_user_registration
    get "signin" => "sessions#new", :as => :new_user_session
    post "signin" => "sessions#create", :as => :user_session
    delete "signout" => "sessions#destroy", :as => :destroy_user_session
  end

  resource :me, controller: :current_user, only: [] do
    get :otp
    get :otp_qrcode
    post :otp_backup_codes
    post :enable_otp
    post :disable_otp
  end

  resource :account, only: %i[edit update]

  resource :password, only: %i[edit update]

  resources :invoices do
    collection do
      put "archive" => "invoices#archive_all"
    end
    member do
      put :generate_positions
      put :charge
      put :pay
      put :archive
      put :send_mail
      post :send_test_mail
      get "/pdf/:pdf" => "invoices#pdf", :as => :pdf, :defaults => {format: :pdf}
      get "/timesheet-pdf/:pdf" => "invoices#timesheet", :as => :timesheet_pdf, :defaults => {format: :pdf}
    end
  end

  resources :offers do
    member do
      get "/pdf/:pdf" => "offers#pdf", :as => :pdf, :defaults => {format: :pdf}
    end
  end

  resource :timesheet, only: [:show]

  resource :template, only: [] do
    template "blank"
    template "datepicker"
    template "month_timers"
    template "day_timesheets"
    template "week_timesheets"
    template "timer_modal_timesheets"
    template "task_modal_timesheets"
    template "index_logbooks"
  end

  resources :positions, only: %i[new destroy]

  resources :customers, only: %i[edit update]
  resources :projects, except: [:destroy] do
    member do
      put :unarchive
    end

    resources :tasks, only: %i[index create]
  end

  resources :timers, only: [] do
    collection do
      get :uninvoiced
    end
  end

  resources :expenses, except: [:show]
  resources :expense_imports, only: %i[new create]

  resource :dropbox, controller: "dropbox", only: [:show] do
    collection do
      get :start
      get :activate
      get :deactivate
    end
  end

  draw :frontend_routes

  get "impressum" => "base#impressum"
  get "privacy" => "base#privacy"
  get "terms" => "base#terms"

  match "404" => "errors#not_found", :via => :all
  match "422" => "errors#server_error", :via => :all
  match "500" => "errors#server_error", :via => :all

  root to: "base#index"
end

app/models/account.rb
# frozen_string_literal: true

class Account < ApplicationRecord
  has_many :users, dependent: :destroy
  has_many :invoices, dependent: :destroy
  has_many :offers, dependent: :destroy
  has_many :tax_rates, dependent: :destroy
  has_many :customers, dependent: :destroy
  has_many :projects, through: :customers
  has_many :tasks, through: :projects
  has_many :timers, through: :tasks
  has_many :expenses, dependent: :destroy

  store_accessor :settings, :tax, :provision
  store_accessor :bank_account, :bank, :account_number, :bank_code, :iban, :bic
  store_accessor :services, :dropbox_user, :dropbox_token
  store_accessor :mailing, :default_from, :signature
  store_accessor :contact_information, :address, :country, :public_email, :telefon, :fax, :website

  validates :name, :users, :plan, presence: true
  # rubocop:disable Rails/UniqueValidationWithoutIndex empty subdomain prevents a unique index
  validates :subdomain, uniqueness: true, allow_blank: true
  # rubocop:enable Rails/UniqueValidationWithoutIndex
  validates :subdomain, exclusion: {in: %w[www app admin api backend reckoning]}
  validates_associated :users
  validates :stripe_token, :stripe_email, presence: true, on: :create, if: :on_paid_plan?

  accepts_nested_attributes_for :users

  before_save :calculate_office_percent
  before_create :set_trail_end_date

  def uninvoiced_amount
    projects.active.where("rate IS NOT NULL AND rate > 0").sum do |project|
      project.timer_values_uninvoiced * project.rate
    end + invoices.includes(:customer, :project).order("date DESC").created.sum(:value)
  end

  def on_paid_plan?
    !on_plan?(:free)
  end

  def calculate_office_percent
    return if deductible_office_space.blank? || office_space.blank?

    self.deductible_office_percent = (100.0 * deductible_office_space / office_space).ceil
  end

  def set_trail_end_date
    return if on_plan?(:free)

    self.trail_used = true
    self.trail_end_at = 30.days.from_now
  end

  def provision_value
    return if provision.blank?

    current_invoices = invoices.includes(:customer, :project).order("date DESC").paid_in_year(Time.zone.now.year)

    current_expenses = Expense.normalized(
      expenses.without_insurances.without_afa.year(Time.zone.now.year).to_a,
      year: Time.zone.now.year
    ).sum do |expense|
      expense.usable_value(Time.zone.now.year)
    end

    open_afa_expenses = expenses.filter_type(:afa).sum do |expense|
      expense.afa_value(Time.zone.now.year)
    end

    (current_invoices.sum(:value) - current_expenses - open_afa_expenses) / 100 * provision.to_i
  end

  def last_provision_value
    return if provision.blank?

    last_invoices = invoices.includes(:customer, :project).order("date DESC").paid_in_year(Time.zone.now.year - 1)
    last_expenses = expenses.without_insurances.year(Time.zone.now.year - 1).to_a.sum do |expense|
      expense.usable_value(Time.zone.now.year - 1)
    end
    open_afa_expenses = expenses.filter_type(:afa).reject do |expense|
      expense.afa_value(Time.zone.now.year - 1).zero?
    end.sum do |expense|
      expense.afa_value(Time.zone.now.year - 1)
    end
    (last_invoices.sum(:value) - last_expenses - open_afa_expenses) / 100 * provision.to_i
  end

  def dropbox?
    dropbox_token.present?
  end

  def on_plan?(on_plan)
    return if plan.blank?

    plan.to_sym == on_plan
  end
end

app/controllers/accounts_controller.rb
# frozen_string_literal: true

class AccountsController < ApplicationController
  include ResourceHelper

  before_action :check_registration_setting, only: %i[new create]
  before_action :set_active_nav, except: %i[new create]
  before_action :authenticate_user!, except: %i[new create]
  skip_authorization_check only: %i[new create]

  def new
    @active_nav = "registration"
    redirect_to new_user_session_path if current_account.present?
    @account = Account.new plan: params[:plan]
    @account.users.build
    render layout: "landing_page"
  end

  def edit
    authorize! :update, account
  end

  def create
    @active_nav = "registration"
    if account.save
      redirect_to new_user_session_path, flash: {success: resource_message(:account, :create, :success)}
    else
      render "new", alert: resource_message(:account, :create, :failure), layout: "landing_page"
    end
  end

  def update
    authorize! :update, account
    if account.update(account_params)
      redirect_to "#{edit_account_path}#{hash}", flash: {success: resource_message(:account, :update, :success)}
    else
      flash.now[:alert] = resource_message(:account, :update, :failure)
      render "edit"
    end
  end

  private def set_active_nav
    @active_nav = "account"
  end

  private def account_params
    @account_params ||= params.require(:account).permit(
      :plan, :tax, :vat_id, :provision, :bank, :account_number, :bank_code, :bic, :iban,
      :signature, :name, :address, :country, :public_email, :subdomain, :telefon, :fax, :website,
      :stripe_email, :stripe_token, :office_space, :deductible_office_space, :offer_headline,
      users_attributes: %i[email password password_confirmation]
    )
  end

  private def account
    @account ||= current_account
    @account ||= Account.new account_params
  end
  helper_method :account

  private def hash
    params.fetch(:hash, "")
  end

  private def check_registration_setting
    return if registration_enabled? || params[:stripe_test].present?

    redirect_to root_path
  end
end

app/controllers/backend/accounts_controller.rb
# frozen_string_literal: true

module Backend
  class AccountsController < BaseController
    include ResourceHelper

    before_action :set_active_nav

    # get: /backend/accounts
    def index
      @accounts = Account.all
        .order(created_at: :desc)
        .page(params.fetch(:page, nil))
        .per(20)
    end

    # get: /backend/accounts/new
    def new
      @account = Account.new
      account.users.build
    end

    # post: /backend/accounts
    def edit
    end

    # get: /backend/accounts/:id/edit
    def create
      generated_password = Devise.friendly_token.first(16)
      user = account.users.first
      user.created_via_admin = true
      user.password = generated_password
      user.password_confirmation = generated_password
      if account.save
        redirect_to backend_accounts_path, notice: resource_message(:account, :create, :success)
      else
        render "new", error: resource_message(:account, :create, :failure)
      end
    end

    # patch: /backend/accounts/:id
    def update
      if account.update(account_params)
        redirect_to backend_accounts_path, notice: resource_message(:account, :update, :success)
      else
        render "edit", error: resource_message(:account, :update, :failure)
      end
    end

    def destroy
      if account.destroy
        redirect_to backend_accounts_path, notice: resource_message(:account, :destroy, :success)
      else
        redirect_to backend_accounts_path, error: resource_message(:account, :destroy, :failure)
      end
    end

    private def account_params
      params.require(:account).permit(:plan, :name, :feature_expenses, :feature_logbook, users_attributes: [:email])
    end

    private def account
      @account ||= Account.where(id: params.fetch(:id, nil)).first
      @account ||= Account.new(account_params)
    end
    helper_method :account

    private def set_active_nav
      @active_nav = "backend_accounts"
    end
  end
end

app/controllers/backend/base_controller.rb
# frozen_string_literal: true

module Backend
  class BaseController < ApplicationController
    before_action :verify_admin
    layout "backend"

    skip_authorization_check

    def dashboard
      @active_nav = "backend_dashboard"
      @settings = Rails.application.credentials
      @latest_users = User.limit(10).order("created_at DESC")
      @users_count = User.count
    end

    private def verify_admin
      redirect_to root_url unless current_user.try(:admin?)
    end
  end
end

app/controllers/backend/users_controller.rb
# frozen_string_literal: true

module Backend
  class UsersController < BaseController
    include ResourceHelper

    before_action :set_active_nav

    # get: /backend/users
    def index
      @users = User.all
        .order("#{sort_column} #{sort_direction}")
        .page(params.fetch(:page, nil))
        .per(20)
    end

    # get: /backend/users/new
    def new
    end

    # post: /backend/users
    def edit
    end

    def send_welcome
      if user.send_confirmation_instructions
        redirect_to backend_users_path, notice: I18n.t(:"messages.user.send_welcome.success")
      else
        redirect_to backend_users_path, notice: I18n.t(:"messages.user.send_welcome.failure")
      end
    end

    # get: /backend/users/:id/edit
    def create
      password = Devise.friendly_token.first(30)
      @user = User.new(
        user_params.merge(
          password: password,
          password_confirmation: password
        )
      )
      user.skip_confirmation_notification!
      if user.save
        redirect_to backend_users_path, notice: resource_message(:user, :create, :success)
      else
        render "new", error: resource_message(:user, :create, :failure)
      end
    end

    # patch: /backend/users/:id
    def update
      if user.update(user_params)
        redirect_to backend_users_path, notice: resource_message(:user, :update, :success)
      else
        render "edit", error: resource_message(:user, :update, :failure)
      end
    end

    def destroy
      if user.destroy
        redirect_to backend_users_path, notice: resource_message(:user, :destroy, :success)
      else
        redirect_to backend_users_path, error: resource_message(:user, :destroy, :failure)
      end
    end

    def sort_column
      User.column_names.include?(params[:sort]) ? params[:sort] : "id"
    end
    helper_method :sort_column

    private def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :admin, :enabled)
    end

    private def user
      @user ||= User.where(id: params.fetch(:id, nil)).first
      @user ||= User.new
    end
    helper_method :user

    private def set_active_nav
      @active_nav = "backend_users"
    end
  end
end

app/views/backend/accounts/_list.slim
.panel.panel-list.panel-default
  .panel-heading
    .panel-title
      .row
        .col-xs-8.col-md-4.name Name
  .list-group
    = render partial: "backend/accounts/show", collection: @accounts, as: :account

app/views/backend/accounts/_show.slim
a.list-group-item href=edit_backend_account_path(account)
  b = account.name

app/views/backend/accounts/edit.slim
- content_for :title do
  = I18n.t(:"meta.title.backend.account.edit")
.row#account-edit
  .col-xs-12.col-md-12
    .row
      .col-xs-12.col-md-8
        h1
          = I18n.t(:"headlines.backend.account.edit", account: account.name)

      .col-xs-12.col-md-4
        .btn-group.pull-right.resource-nav
          = link_to I18n.t(:"nav.subnav.back"), backend_accounts_path, class: "btn btn-default"

    = form_for [:backend, account] do |form|
      .row
        .col-xs-12.col-md-6.form-group class=form_error?(account, :name)
          = form.label :name
          = form.text_field :name, placeholder: I18n.t(:"helpers.placeholder.account.name"), class: 'form-control'
          small
            = form_errors account, :name
        .col-xs-12
          .checkbox
            = form.check_box :feature_expenses
            label for="account_feature_expenses"
              = I18n.t(:"helpers.label.account.feature_expenses")
        .col-xs-12
          .checkbox
            = form.check_box :feature_logbook
            label for="account_feature_logbook"
              = I18n.t(:"helpers.label.account.feature_logbook")

      = render "shared/forms/submit", path: backend_accounts_path

app/views/backend/accounts/index.haml
- content_for :title do
  = I18n.t(:"meta.title.backend.account.index")
.row#accounts
  .col-xs-12.col-md-12

    .row
      .col-xs-12.col-md-8
        %h1
          = I18n.t(:"headlines.backend.account.index")

      .col-xs-12.col-md-4
        .btn-group.pull-right.resource-nav
          = link_to I18n.t(:"nav.subnav.new_account"), new_backend_account_path, class: "btn btn-primary"

    .row
      .col-xs-12.col-md-6
        .pull-right
          = paginate @accounts

    = render "backend/accounts/list", accounts: @accounts

    .row
      .col-xs-12.col-md-6
        .pull-right
          = paginate @accounts

app/views/backend/accounts/new.slim
- content_for :title do
  = I18n.t(:"meta.title.backend.account.new")
.row#account-new
  .col-xs-12.col-md-12
    .row
      .col-xs-12.col-md-8
        h1
          = I18n.t(:"headlines.backend.account.new")

      .col-xs-12.col-md-4
        .btn-group.pull-right.resource-nav
          = link_to I18n.t(:"nav.subnav.back"), backend_accounts_path, class: "btn btn-default"

    = form_for [:backend, account] do |form|
      = form.hidden_field :plan, value: :free
      .row
        .col-xs-12.col-md-6
          .form-group class=form_error?(account, :name)
            = form.label :name
            = form.text_field :name, placeholder: I18n.t(:"helpers.placeholder.account.name"), class: 'form-control'
            small
              = form_errors account, :name

      = form.fields_for :users, account.users do |fields|
        .row
          .col-xs-12.col-md-6
            .form-group class=form_error?(fields.object, :email)
              = fields.text_field :email, placeholder: I18n.t(:"helpers.placeholder.user.email"), class: 'form-control'
              small
                = form_errors fields.object, :email

      = render "shared/forms/submit", path: backend_accounts_path